### List all messages

GET http://localhost:3000/messages

### Create a New message
POST http://localhost:3000/messages
Content-Type: application/json

{
    "content": "Hi There!"
}

### Get a dparticular message

GET  http://localhost:3000/messages/1231232